### ISSUE TITLE
Doesent work on Termux

### ISSUE THREAD

**Issue by kalvo123** [Manisso/fsociety#102]
## Checkboxes

- [✔ ] Updated fsociety
- [✔ ] Issue does not already exist
- [ ✔] fsociety issue, not a tool issue

## Expected Result
doesent launch
Running it on Termux without root privledges.
>what do?
```bash

```

## Actual Result
$ fsociety
  File "/data/data/com.termux/files/usr/usr/share/doc/fsociety/fsociety.py", line 1194
    print "-------------------------"
          ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("-------------------------")?
```bash

```

**Comment by kalvo123** [comment]
btw whats youre discord?
i cant find it

**Comment by CRO-THEHACKER** [comment]
You can DM me on discord with this issue ID (102) 

My discord is Alison but Hacker, please join the server: https://discord.gg/BaBpuPn

**Comment by J4ck3LSyN** [comment]
Found the issue... Termux launches all 'python' commands as python3. On most Linux distros like Kali it is python2, to fix:
`
cd ../use/bin
nano fsociety
`
Inside you will see something like 
`
python /data/data/com.termux/files/usr/usr/share/doc/fsociety/fsociety.py
`
Simply change it to
`
python2 /data/data/com.termux/files/usr/usr/share/doc/fsociety/fsociety.py
`
Now as far as needing root it is a good idea to have but not needed I was able to launch with no problem.

**Comment by CRO-THEHACKER** [comment]
Oh damn check that out - thanks man!
