### ISSUE TITLE
Dosn't work Ubuntu

### ISSUE THREAD

**Issue by GreatZardasht** [Manisso/fsociety#103]
I don't have Linux but I have Ubuntu Windows 10 and this don't work for it.

**Comment by kianklain** [comment]
email me and give me the code

**Comment by CRO-THEHACKER** [comment]
Hello, could you please tell us what is going on to help you more?

**Comment by Golden18** [comment]
How do i install fsociety in termux?

**Comment by glaydsoncosta** [comment]
Use Kali Linux.

**Comment by CRO-THEHACKER** [comment]
No, you dont **HAVE** to use Kail Linux with fsociety @glaydsoncosta

**Comment by CRO-THEHACKER** [comment]
@Golden18 Please read the README.md there is an vid on how to do it!

**Comment by CRO-THEHACKER** [comment]
This is 10days old, no one is giving me more. Best I can say is use sudo with all of it or reopen with your prob.

Thanks guys
