### ISSUE TITLE
nmap

### ISSUE THREAD

**Issue by Ryizz** [Manisso/fsociety#107]
Trying to use nmap from the script gives the error: 
Failed to open normal output file logs/nmap-date-time for writing
QUITTING!

**Comment by Ryizz** [comment]
Fixed it by editing fsociety.py

**Comment by Mmaaii** [comment]
How did u edit it?

**Comment by Versxxe** [comment]
no edit

水, 12月 23, 2020 at 08:13, Mmaaii <notifications@github.com> が送信：

**Comment by Atiqlaa** [comment]
a... Hello
