### ISSUE TITLE
/usr/local/bin/fsociety: line 2: python: command not found

### ISSUE THREAD

**Issue by G-pw** [Manisso/fsociety#108]
## Checkboxes

- [ ] Updated fsociety
- [ ] Issue does not already exist
- [ ] fsociety issue, not a tool issue

## Expected Result

fsociety launch

## Actual Result

/usr/local/bin/fsociety: line 2: python: command not found

**Comment by CRO-THEHACKER** [comment]
Pushing new update, give me a min to update that line.

**Comment by CRO-THEHACKER** [comment]
#110

**Comment by CRO-THEHACKER** [comment]
Wait this is in python2, not 3. Please install python2!

`sudo apt install python`

**Comment by Jkay21** [comment]
hi! I m still having the same issues even after installing python 2
any help?

**Comment by DARKDRUG** [comment]
I am also finding bro 😭

**Comment by dananothername** [comment]
that link helped 
but how to use the tool there is no guide
