### ISSUE TITLE
: /usr/local/bin/fsociety: line 2: python: command not found

### ISSUE THREAD

**Issue by AbimbolaObadare** [Manisso/fsociety#110]
## Checkboxes

- [ ] Updated fsociety
- [ ] Issue does not already exist
- [ ] fsociety issue, not a tool issue

## Expected Result

```bash

```

## Actual Result

```bash

```

**Comment by CRO-THEHACKER** [comment]
#108 Fixed with installing python2.

`sudo apt install python`
