### ISSUE TITLE
Line 1194 in python  it is showing an error please solve this immediately

### ISSUE THREAD

**Issue by Akashsena** [Manisso/fsociety#112]
## Checkboxes

- [ ] Updated fsociety
- [ ] Issue does not already exist
- [ ] fsociety issue, not a tool issue

## Expected Result

```bash

```

## Actual Result

```bash

```

**Comment by gabbanaesteban** [comment]
"solve this immediately"
Are you paying support or something?
Too rude for something free ;)

**Comment by CRO-THEHACKER** [comment]
no, not at all. I just asked for the error that happend for you.

**Comment by thehappydinoa** [comment]
Hi, if there is still an issue please consider creating a new issue with more information.
