### ISSUE TITLE
centos 8 python 2 

### ISSUE THREAD

**Issue by yqelcodes** [Manisso/fsociety#113]
## Checkboxes

- [ ] Updated fsociety
- [ ] Issue does not already exist
- [ ] fsociety issue, not a tool issue

## Expected Result

```bash

```install? 

## Actual Result

```bash

```python2 fsociety.py
python2: can't open file 'fsociety.py': [Errno 2] No such file or directory

**Comment by thehappydinoa** [comment]
Hi, this is actually an issue for [`fsociety-team/fsociety`](https://github.com/fsociety-team/fsociety). It seems as if you don't have the right version of Python added to your PATH, but I can investigate further with the updated version
