### ISSUE TITLE
hack website for me

### ISSUE THREAD

**Issue by hussainFSOCIETY** [Manisso/fsociety#115]
www.joysclubs.com  
hack this website please
sathamhussain181@gmail.com

**Comment by CRO-THEHACKER** [comment]
Legit NO one is going to do that for you...

**Comment by hussainFSOCIETY** [comment]
Why not

**Comment by CRO-THEHACKER** [comment]
It's not as easy as you think it is; and this repo isn't going to help you hack to to much whatsoever. 

Close this issue in git because this is not an issue with the toolkit.

**Comment by hussainFSOCIETY** [comment]
I know what you are saying is fact,but  i lost money in that betting site,
I'm hopeless now

**Comment by CRO-THEHACKER** [comment]
I'm sorry no one here is going to help.. Please close this issue.

**Comment by hussainFSOCIETY** [comment]
Can you hack that site for me please,  hack means not to do bad stuff, i
just want you to download all the data from the server except people
credentials

**Comment by CRO-THEHACKER** [comment]
What you are saying is illegal in many countries

**Comment by hussainFSOCIETY** [comment]
No not really, I'm asking for you to download the websites's stored data
except credentials,  i don't ask for someone password

**Comment by CRO-THEHACKER** [comment]
That isnt how it works...

**Comment by hussainFSOCIETY** [comment]
Then how?

**Comment by CRO-THEHACKER** [comment]
Please close issues...

**Comment by hussainFSOCIETY** [comment]
Ok,  but

**Comment by Odsku** [comment]
Its still illegal because you are getting unauthorized access to that website

**Comment by CRO-THEHACKER** [comment]
> Its still illegal because you are getting unauthorized access to that website

Thank you lol @hussainFSOCIETY please close this issue :)

**Comment by Wioaoaoaoapa** [comment]
I feel sorry for you for losing money

**Comment by hussainFSOCIETY** [comment]
I almost forgot about losing money
You can drop it

**Comment by Wioaoaoaoapa** [comment]
Try ddosing the site

**Comment by Wioaoaoaoapa** [comment]
Maybe I'll destroy the site in the future since it's a gambling scam

**Comment by Wioaoaoaoapa** [comment]
I'm still a script kiddie but I'll try upgrading society or creating something just like fsociety

**Comment by hussainFSOCIETY** [comment]
That site was removed by government 2 years ago

**Comment by hussainFSOCIETY** [comment]
Good luck with your work
