### ISSUE TITLE
Termux

### ISSUE THREAD

**Issue by demonzona** [Manisso/fsociety#122]

**Comment by CRO-THEHACKER** [comment]
How can I assist you?

**Comment by khansaad1275** [comment]
line 2 :  Python command not found,What should i do?

**Comment by CRO-THEHACKER** [comment]
> line 2 :  Python command not found,What should i do?

Make sure your using a Linux distro like Ubuntu or Parrot OS and install python from apt command line with:

```
sudo apt-get install python2 python2-dev
``` 

And then run the install file. 

```
sudo bash ./install.sh
```

**Comment by thehappydinoa** [comment]
Hi, closing as this appears to have been solved.
