### ISSUE TITLE
i wanna go to the discord

### ISSUE THREAD

**Issue by hubahuba2016** [Manisso/fsociety#125]
old habbits.. to leave and rejoin.. pls let me in

**Comment by CRO-THEHACKER** [comment]
Oldfsociety bans can be revoked if you contact them via email.

**Comment by CRO-THEHACKER** [comment]
To contact 5/9 visit fiveninedark.com

**Comment by Wioaoaoaoapa** [comment]
Hey how do I fix syantax error
