### ISSUE TITLE
Error in Ubuntu

### ISSUE THREAD

**Issue by Pope4464** [Manisso/fsociety#127]
My error is 
File "/root/.fsociety/fsociety.py", line 1194
    print "-------------------------"
          ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("-------------------------")?

Yes i ran in root.

**Comment by CRO-THEHACKER** [comment]
Your running python3, find python3 fsociety tool-kit [here](https://fsociety.dev/)

to fix current issue - download python2, python2-dev & add ppa with this one line:

Ubuntu/Deb:
```
sudo add-apt-repository ppa:deadsnakes/ppa && sudo apt update \
sudo apt-get install python2.6 python2.6-dev \
python2.6 fsociety.py```

This will make you able to run this project.

**Comment by Pope4464** [comment]
> Your running python3, find python3 fsociety tool-kit [here](https://fsociety.dev/)
> 
> to fix current issue - download python2, python2-dev & add ppa with this one line:
> 
> Ubuntu/Deb:
> 
> ```
> sudo add-apt-repository ppa:deadsnakes/ppa && sudo apt update \
> sudo apt-get install python2.6 python2.6-dev \
> python2.6 fsociety.py```
> 
> This will make you able to run this project.
> ```

Thanks a lot!!

**Comment by Pope4464** [comment]
Will there be an update to python 3?

**Comment by CRO-THEHACKER** [comment]
> Will there be an update to python 3?
> 

As I said, the new fsociety tool kit can be found in my other post, this project is old and EOL (End-of-Life)very soon

**Comment by Pope4464** [comment]
Ah silly me using python2 script with python3. Thanks a lot tho!
