### ISSUE TITLE
There is are two typos in this line, 'mallicious' & 'pishing'

### ISSUE THREAD

**Issue by Vandeerer** [Manisso/fsociety#129]
https://github.com/Manisso/fsociety/blob/78eaf77f71a2a13dcc31b4fa94da9a1f6a23010d/fsociety.py#L242

**Comment by thehappydinoa** [comment]
Hi, this version is not being actively maintained. Please see our updated version [`fsociety-team/fsociety`](https://github.com/fsociety-team/fsociety)
