### ISSUE TITLE
Error in Code: Line 185

### ISSUE THREAD

**Issue by BlackBatman1980** [Manisso/fsociety#130]

**Comment by CRO-THEHACKER** [comment]
Just use the new version:

[Download here](https://fsociety.dev/)

**Comment by BlackBatman1980** [comment]
Is there a windows version?

**Comment by CRO-THEHACKER** [comment]
You cannot not use windows btw - Linux only

**Comment by BlackBatman1980** [comment]
Awwww. Ok. Thanks though

**Comment by CRO-THEHACKER** [comment]
> Awwww. Ok. Thanks though

If you want to learn downloaded VBox and make an Linux VM and learn the hobby. Using scripts only cannot hack much ;-;
