### ISSUE TITLE
SyntaxError: Line 185

### ISSUE THREAD

**Issue by BlackBatman1980** [Manisso/fsociety#131]
There is a syntax error:
File "<string>", line 185
    with open(configFile, 'wb') as configfile:
            ^
SyntaxError: invalid syntax

This is causing the program to not work so I basically have more dead weight in my system. I am using windows but I am running this in python2. Pls, help.

**Comment by CRO-THEHACKER** [comment]
Also you cannot not use windows - use Linux..

**Comment by BlackBatman1980** [comment]
Aight
