### ISSUE TITLE
trojan in your zip file 

### ISSUE THREAD

**Issue by SamDvl-07** [Manisso/fsociety#133]
## Checkboxes

- [ ] Updated fsociety
- [x] Issue does not already exist
- [x] fsociety issue, not a tool issue

## Expected Result

```bash

```

## Actual Result

```bash

```

**Comment by SamDvl-07** [comment]
https://ibb.co/HG1WJhW

**Comment by CRO-THEHACKER** [comment]
1  you have to use Linux
2  Use git to download 
3  this repo isn't supported anymore, please use the new version. https://fsociety.dev
