### ISSUE TITLE
An error appears after running on Termux

### ISSUE THREAD

**Issue by OweRam** [Manisso/fsociety#135]
~/fsociety $ > fsociety
  File "/data/data/com.termux/files/usr/usr/share/doc/fsociety/fsociety.py", line 1194
    print "-------------------------"
          ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("-------------------------")?

## Checkboxes

- [ ] Updated fsociety
- [ ] Issue does not already exist
- [ ] fsociety issue, not a tool issue

## Expected Result

```bash

```

## Actual Result

```bash

```

**Comment by calheiros** [comment]
Install python2:
```
apt update && apt upgrade
apt install python2

```
change script to use python 2 instead python 3:

`sed -i 's/python /python2 /' `which fsociety``
