### ISSUE TITLE
When i tried using the fsociety cmd this came up 

### ISSUE THREAD

**Issue by Yuma-Tsushima07** [Manisso/fsociety#136]
I have installed python 3 and 2 also installed fsociety but when it said to type ```fsociety``` it didnt work and came up with an error.

```Red@Laptop:~/fsociety$ fsociety
/usr/local/bin/fsociety: line 2: python: command not found
```
can anyone help me... if so thats would be great

**Comment by JaasirQureshi** [comment]
Im guessing you need to create environment variables for your python directory.

**Comment by Yuma-Tsushima07** [comment]
i fixed this anyways thanks for your help

**Comment by Killya421** [comment]
Same problem how did solve it ?
