### ISSUE TITLE
Importing Python 3 stuff

### ISSUE THREAD

**Issue by Derjyn** [Manisso/fsociety#17]
requests is getting imported, which is Python 3 only. Commenting out the line allows fsociety to execute, although not sure how requests is being used. Might want to look things over and make certain you don't have version creep hitting this.

**Comment by souvikhaldar** [comment]
I too commented out requests then it worked!

**Comment by thehappydinoa** [comment]
Thank you, I believe it is required by one or more of the external tools, I will look into it tho

**Comment by thehappydinoa** [comment]
Thank you, I believe it is required by one or more of the external tools, I will look into it tho

**Comment by souvikhaldar** [comment]
I too was wondering how to manage without requests module!

**Comment by thehappydinoa** [comment]
Fixed in #20
