### ISSUE TITLE
Information Gathering/Host to IP

### ISSUE THREAD

**Issue by dobinoo** [Manisso/fsociety#18]
It's not a flaw, it's more a design issue. After entering a valid hostname, tool correctly print the IP address , but automatically change to main screen of program and scroll down. By default size (kali terminal) it looks like it didn't show anything. So some pause, or "press key to continue" would be nice :). It's just an idea , or guide for those who are thinking it doesn't work , like me :D .

**Comment by Manisso** [comment]
Thnx Bro We Will Do It

**Comment by thehappydinoa** [comment]
This has been implemented.
