### ISSUE TITLE
Misleading input expectations

### ISSUE THREAD

**Issue by akaars** [Manisso/fsociety#19]
Reproduction scenario:
1) Install fsociety on regular Ubuntu machine (not kali)
2) In fsociety start menu select (3) for Wireless testing and then select (1) for reaver.
The following message displayed:

>       Reaver has been designed to be a robust and practical attack against Wi-Fi Protected Setup
>       WPS registrar PINs in order to recover WPA/WPA2 passphrases. It has been tested against a
>       wide variety of access points and WPS implementations
>       1 to accept / 0 to decline

But the proposed (and the only allowed) input is: y / n

**Comment by thehappydinoa** [comment]
I will look into this, I believe this is part of reavers input

**Comment by akaars** [comment]
Not only for reaver, I observed exactly the same behavior for pixiewps.
I'm not really sure how is the integration between fsociety and the linux disto expected to be. If fsociety supposed to work properly explicitly as a part of Kali so may be this is good enough and you shouldn't really care about all those small details since those questions will never be exposed to Kali user.
Otherwise - well, it will probably  require a lot of work to do :)

**Comment by thehappydinoa** [comment]
@akaars I actually only use kali for this, but I am unsure on how it responds on ubuntu. Does it work when you type 'y'?

**Comment by akaars** [comment]
Actually it doesn't :) It fails on installation due to insufficient permissions.
It looks like:

 

>      Reaver has been designed to be a robust and practical attack against Wi-Fi Protected Setup
>       WPS registrar PINs in order to recover WPA/WPA2 passphrases. It has been tested against a
>       wide variety of access points and WPS implementations
>       1 to accept / 0 to decline
>         
> y / n :Y
> E: Could not open lock file /var/lib/dpkg/lock - open (13: Permission denied)
> E: Unable to lock the administration directory (/var/lib/dpkg/), are you root?
> Cloning into 'reaver-wps-fork-t6x'...
> remote: Counting objects: 2438, done.
> remote: Compressing objects: 100% (61/61), done.
> remote: Total 2438 (delta 90), reused 113 (delta 76), pack-reused 2300
> Receiving objects: 100% (2438/2438), 1.91 MiB | 1.42 MiB/s, done.
> Resolving deltas: 100% (1547/1547), done.
> sh: 1: ./configure: not found
> make: *** No targets specified and no makefile found.  Stop.

**Comment by akaars** [comment]
Upd:
sorry for misleading you.
In pixiewps there is an installation problem which is not related to the described issue, but the behavior is not the same, which means the mentioned behavior is indeed reaver behavior as you mentioned in one of the previous comments. 
So you can close it as "not a bug", sorry for wasting your time :(

**Comment by thehappydinoa** [comment]
Ok sounds good, could you please create a new issue around this pixelwps installation issue?
