### ISSUE TITLE
Arachni doesnt run 

### ISSUE THREAD

**Issue by theonlydoo** [Manisso/fsociety#22]
related to #21 :
```
/usr/bin/env: ruby: No such file or directory
```

on arachni install

**Comment by thehappydinoa** [comment]
Could we get some more info on what platform you are using?

**Comment by theonlydoo** [comment]
same as #21, git clone / docker build / docker run (so python2.7 docker images as seen in your dockerfile)

**Comment by thehappydinoa** [comment]
Ok thank you. I am honestly not an expert on Docker but hopefully I can get a fix working. Suggestions are always welcome
