### ISSUE TITLE
Enhancement Ideas

### ISSUE THREAD

**Issue by thehappydinoa** [Manisso/fsociety#24]
Hi All,
I just wanted to start the conversation about possible enhancements to fsociety. Comment down below what you would like to see included in the next update. Thanks ☺️

List of Programs to Add:
- [ ] FatRat

**Comment by StainYY** [comment]
FatRat Penetration testing framework!

**Comment by StainYY** [comment]
fsociety needs root to run setoolkit on termux but as of termux policy it runs on non-rooted environment so please make it non-rooted and also add fatrat to it!
 thank you

**Comment by huangsam** [comment]
What if there was a GitHub page for highlighting this repository? I think that would be pretty cool.

**Comment by thehappydinoa** [comment]
@huangsam like a wiki?

**Comment by huangsam** [comment]
@thehappydinoa like [this from Bootstrap](https://getbootstrap.com/) or [that from Vue](https://vuejs.org/)

**Comment by huangsam** [comment]
It would probably involve purchasing a custom DNS or just using the default DNS from GitHub.

**Comment by thehappydinoa** [comment]
Oh cool, would you like to work on that I'll make a repo and get a custom dns

**Comment by huangsam** [comment]
It's as simple as having a separate `gh-pages` branch. Not sure if you need a whole new repo.

Typically someone configures it like so from the repository settings page:

<img width="741" alt="screen shot 2018-02-09 at 10 21 04 pm" src="https://user-images.githubusercontent.com/515617/36059182-8f800e44-0de7-11e8-8a2d-7b0c1b0da217.png">

There's an entry for providing a custom DNS entry.

You can learn more about GitHub Pages [here](https://pages.github.com/).

**Comment by thehappydinoa** [comment]
Cool

**Comment by huangsam** [comment]
https://github.com/Manisso/fsociety/pull/32

**Comment by huangsam** [comment]
Thanks for the merge @thehappydinoa - looking forward to seeing the content deployed to the web

**Comment by thehappydinoa** [comment]
@huangsam ofc thank you for the quick, simple, and beautiful design.

**Comment by thehappydinoa** [comment]
@huangsam Let me know what you think: [fsociety.thehappydinoa.me](http://fsociety.thehappydinoa.me/)

**Comment by huangsam** [comment]
@thehappydinoa looks good but could use some more work. Created #33 to help resolve some issues. Also you should add it here:

<img width="1000" alt="screen shot 2018-02-10 at 6 56 21 pm" src="https://user-images.githubusercontent.com/515617/36068871-1e13128a-0e94-11e8-9fd4-fa1224ddadfe.png">

See how Vue does it:

<img width="996" alt="screen shot 2018-02-10 at 6 57 07 pm" src="https://user-images.githubusercontent.com/515617/36068882-3f1f5ec0-0e94-11e8-8b0a-fbedcbc0e67d.png">

**Comment by thehappydinoa** [comment]
@Manisso could you do this, I don't think I am allowed to as colaborator

**Comment by huangsam** [comment]
@thehappydinoa is the site up anymore? Are you guys in the works of registering another DNS?

**Comment by thehappydinoa** [comment]
@huangsam I just cannot be responsible for hosting it but if someone wanted to donate a dns and or hosting that would be amazing.
