### ISSUE TITLE
Installation problems with Python2 env

### ISSUE THREAD

**Issue by Vanclief** [Manisso/fsociety#28]
After install, when trying to run fsociety I am getting the following error:

``` 
  File "/usr/share/doc/fsociety/fsociety.py", line 705
    """
      ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(int """
      Reaver has been designed to be a robust and practical attack against Wi-Fi Protected Setup
      WPS registrar PINs in order to recover WPA/WPA2 passphrases. It has been tested against a
      wide variety of access points and WPS implementations
      1 to accept / 0 to decline
        """)?
```
I do have Python2 installed.

`/usr/bin/env python2` contains Python 2.7.14

Manually executing `python2 /usr/share/doc/fsociety/fsociety.p` launches the menu. However whenever selecting an option, it returns me immediately to the menu so I can't see what the error is.

Im running Arch linux.

**Comment by thehappydinoa** [comment]
Hi, so I am actually trying to rework all of the functions in the classes at this moment, to prevent this very problem

**Comment by thehappydinoa** [comment]
Also we currently only support debian-based operating systems

**Comment by thehappydinoa** [comment]
Although if you want to implement arch Linux support I would be glad to merge

**Comment by Vanclief** [comment]
@thehappydinoa thanks for the heads-up, will take a look at it.

**Comment by metalcamp** [comment]
@Vanclief have you tried virtualenv?

**Comment by thehappydinoa** [comment]
Ya I would suggest `virtualenv` and maybe give kali a try

**Comment by Vanclief** [comment]
Hey, sorry I haven't had time to check this out.  I was using pipenv, but will try with virtualenv to see if there is any difference.
