### ISSUE TITLE
What is This 

### ISSUE THREAD

**Issue by alishawky212** [Manisso/fsociety#3]
Traceback (most recent call last):
  File "fsociety.py", line 34, in <module>
    import requests
ImportError: No module named requests

**Comment by Manisso** [comment]
Can You tell me what os you are using
 
ps:Use python mobil.py

**Comment by alishawky212** [comment]
Using Ubuntu

**Comment by Manisso** [comment]
Use mobil.py if they Don't Work Tell Me 
Thnx For Using Fsociety :+1:

**Comment by AI35** [comment]
To Fix this proplem:
pip install requests

**OR use mobil.py**

**Comment by alishawky212** [comment]
thanks it worked
