### ISSUE TITLE
error 

### ISSUE THREAD

**Issue by c0ll3cti0n** [Manisso/fsociety#36]
$ fsociety
  File "/data/data/com.termux/files/usr/usr/share/doc/fsociety/fsociety.py", line 1136
    except(), message:
            ^
SyntaxError: invalid syntax

I am using termux

**Comment by thehappydinoa** [comment]
Refer to #37 for a solution

**Comment by eplusp** [comment]
Just do this:
$Cd  /data/data/com.termux/files/usr/bin
$ fsociety

And then 
Just find python command and replace python2
Save it 
Done !

**Comment by eplusp** [comment]
Just do this:
$Cd /data/data/com.termux/files/usr/bin
$ nano fsociety

And then
Just find 'python' text and replace 'python2'
Save it
Done !
