### ISSUE TITLE
Python and Git commands are not recognized

### ISSUE THREAD

**Issue by phtom** [Manisso/fsociety#4]
Hi,

I was trying to run your project on Windows 10, using python.
First of all, i couldn't run it from CMD by writting this: python fsociety.py
Second, i would not be able to run it because python was not recongized even after being installed.
At last i runned it from pythom cmd. The menu works, but when attempting to run a tool, it does not recognize the "git" or "python" .
I cant run any tool from your fsociety tool compilation.
--
I am not an expert at all but sincerly i dont work much too with python.
Thanks in advance,

**Comment by Manisso** [comment]
**On Windows You Can Just Use 7 Private Hacking But If You Are Using Windows You Can Run The Script On Google Cloud Free Console**
## Enjoy Fsociety Tools With  [https://console.cloud.google.com/cloudshell/editor?project=&pli=1&shellonly=true](Google Cloud Console)

**Comment by phtom** [comment]
Thank you very much! Its working!
