### ISSUE TITLE
Tools dnsenum not available from apt-get using 2.7-slim

### ISSUE THREAD

**Issue by Sh4d1** [Manisso/fsociety#40]
Hello,

I just saw that when using brutex in Docker, the install.sh script doesn't work since `dnsenum` is not available in the repo. Would it be better to use `kalilinux/kali-linux-docker` as base image ? Or finding a way to install the tool another way ? 

What do you think ?

Cheers,

Patrik

**Comment by CRO-THEHACKER** [comment]
Please reopen if not already fixed. Thanks!
