### ISSUE TITLE
XSStrike : ImportError: No module named mechanize

### ISSUE THREAD

**Issue by SundownDEV** [Manisso/fsociety#51]
## Checkboxes

- [x] Updated fsociety
- [x] Issue does not already exist
- [ ] fsociety issue not a tool issue

Installed XSStrike and get this error at the execution

```bash
Traceback (most recent call last):
  File "/var/www/Infosec/fsociety/tools/XSStrike/xsstrike", line 5, in <module>
    import mechanize # To make request to webpages
ImportError: No module named mechanize

Click [Return] to continue
Completed, click return to go back
```

**Comment by thehappydinoa** [comment]
In the meantime please run `pip install mechanize`

**Comment by SundownDEV** [comment]
Installed mechanize, the error has changed : 

```
Traceback (most recent call last):
  File "/var/www/Infosec/fsociety/tools/XSStrike/xsstrike", line 8, in <module>
    from prettytable import PrettyTable # Module for print table of results
ImportError: No module named prettytable
```

so I installed PrettyTable too, then fuzzywuzzy. **You should add this in doc** : 

`pip install mechanize prettytable fuzzywuzzy`

It works but getting a warning : 

~~~
/usr/local/lib/python2.7/dist-packages/fuzzywuzzy/fuzz.py:35: UserWarning: Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning
  warnings.warn('Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning')
~~~

`sudo apt-get install python-levenshtein` fix the problem.

also getting an error at ending : 

~~~
Unable to init server: Unable to connect : Connection refused
Error: cannot open display: :0
[8639:8639:0330/100659.647849:ERROR:zygote_host_impl_linux.cc(90)] Running as root without --no-sandbox is not supported. See https://crbug.com/638180.
No protocol specified
Unable to init server: Unable to connect : Connection refused
Error: cannot open display: :0
/usr/bin/xdg-open: 778: /usr/bin/xdg-open: iceweasel: not found
/usr/bin/xdg-open: 778: /usr/bin/xdg-open: seamonkey: not found
/usr/bin/xdg-open: 778: /usr/bin/xdg-open: mozilla: not found
/usr/bin/xdg-open: 778: /usr/bin/xdg-open: epiphany: not found
/usr/bin/xdg-open: 778: /usr/bin/xdg-open: konqueror: not found
/usr/bin/xdg-open: 778: /usr/bin/xdg-open: chromium-browser: not found
[8669:8669:0330/100659.702282:ERROR:zygote_host_impl_linux.cc(90)] Running as root without --no-sandbox is not supported. See https://crbug.com/638180.
/usr/bin/xdg-open: 778: /usr/bin/xdg-open: www-browser: not found
/usr/bin/xdg-open: 778: /usr/bin/xdg-open: links2: not found
/usr/bin/xdg-open: 778: /usr/bin/xdg-open: elinks: not found
/usr/bin/xdg-open: 778: /usr/bin/xdg-open: links: not found
/usr/bin/xdg-open: 778: /usr/bin/xdg-open: lynx: not found
/usr/bin/xdg-open: 778: /usr/bin/xdg-open: w3m: not found
xdg-open: no method available for opening 'http://carte.cgt.fr/departement.php?departement=<sVg%09oNloAd%0d=%0d(confirm)()>'
~~~

**Comment by thehappydinoa** [comment]
@UltimateHackers could you take a look at this for me?

**Comment by UltimateHackers** [comment]
This error is probably thrown by **webbrowser** module which is used to open urls in a graphical browser and looks like you don't have one installed at the moment. If you already have a browser installed on your machine, please try with a different target and ask thr developer of this toolkit to include the latest version of XSStrike.

**Comment by thehappydinoa** [comment]
@UltimateHackers lol so I'm one of he devs, it's directly pulls from your GitHub

**Comment by thehappydinoa** [comment]
@SundownDEV also.make sure to not include the URL in the issue

**Comment by UltimateHackers** [comment]
If its downloads XSStrike from my repo, then this is not a problem related to XSStrike.
As I said earlier, install a graphical browser.

**Comment by SundownDEV** [comment]
@UltimateHackers I don't get why I have to use a graphical browser. I already have firefox installed on Ubuntu.

**Comment by UltimateHackers** [comment]
@SundownDEV Oh so you have Firefox installed? It should work then.
Maybe you are running it in an isolated environment?

**Comment by SundownDEV** [comment]
I have Firefox and it is not running in a isolated env.

**Comment by UltimateHackers** [comment]
Then its not an issue related to XSStrike.
For confirmation, you can download and run XSStrike separately.

**Comment by SundownDEV** [comment]
I'll do it to confirm.

**Comment by SundownDEV** [comment]
@UltimateHackers Getting the exact same issue using your tool from the official repo even with a different URL.

It does not detect firefox : 
`/usr/bin/xdg-open: 778: /usr/bin/xdg-open: mozilla: not found`

Closing as it's an issue with XSStrike.

**Comment by UltimateHackers** [comment]
Well thats strange! XSStrike has been cloned 1,503 times and no one has reported such error.

**Comment by thehappydinoa** [comment]
@SundownDEV are you USING XSS strike with a gui it just command line?

**Comment by SundownDEV** [comment]
@thehappydinoa I clone and use it with command line the exact same way fsociety does it.

**Comment by section1-1** [comment]
i have ecactly the same problem

**Comment by CRO-THEHACKER** [comment]
Just do "pip3 install prettytable && pip3 install mechanize && pip3 fuzzywuzzy", also do "sudo apt-get install python-levenshtein", if not Ubuntu just do " Pip3 install python-levenshtein", that should do the same thing.
