### ISSUE TITLE
Error Exception

### ISSUE THREAD

**Issue by kingdsand** [Manisso/fsociety#54]
## Checkboxes

- [x] Updated fsociety
- [x] Issue does not already exist
- [ ] fsociety issue, not a tool issue

## Expected Result

```bash

```

## Actual Result

```bash

```

me sale este error al ejecutar 

  File "fsociety.py", line 1137
    except(), message:
            ^
SyntaxError: invalid syntax

**Comment by CRO-THEHACKER** [comment]
Must be a tool issue.

**Comment by thehappydinoa** [comment]
This was fixed in #55
