### ISSUE TITLE
Not running.

### ISSUE THREAD

**Issue by hussainasghar** [Manisso/fsociety#60]
When i run fsociety it give me the error.

crazy ~ # fsociety
  File "/home/hussain/.fsociety/fsociety.py", line 1137
    except(), message:
            ^
SyntaxError: invalid syntax

**Comment by magadan10** [comment]
I have the same problem.

**Comment by hussainasghar** [comment]
Looks like the developer team is not maintaining it anymore.

**Comment by CRO-THEHACKER** [comment]
The Turmux installer is fine. This would be a file error. Ill talk to Manisso for making a pushed repo for turmux.
