### ISSUE TITLE
Failed to open normal output file

### ISSUE THREAD

**Issue by apersonlikesc** [Manisso/fsociety#64]
when i run the nmap
this happen even use sudo

Failed to open normal output file logs/nmap-2018-08-30_00:57:02 for writing
QUITTING!

**Comment by apersonlikesc** [comment]
o,i got it

**Comment by ahrixia** [comment]
how did you solve it?

**Comment by CRO-THEHACKER** [comment]
Python2 of f society is no longer supported, check out the new version! [Here](https://fsociety.dev/)
