### ISSUE TITLE
Error when I try to launch xsstrike: python: can't open file '/root/.fsociety/tools/XSStrike/xsstrike': [Errno 2] No such file or directory  Click [Return] to continue

### ISSUE THREAD

**Issue by b4s5** [Manisso/fsociety#68]
## Checkboxes

- [x ] Updated fsociety
- [x ] Issue does not already exist
- [ ?] fsociety issue, not a tool issue

I've updated fsociety and cloned xss from github but when I try to lounch xsstrike it give me this error:

## Actual Result

```bash
python: can't open file '/root/.fsociety/tools/XSStrike/xsstrike': [Errno 2] No such file or directory

Click [Return] to continue

```
but the file is in the directory, why?

EDIT: I've notice that this isn't the only tool that I can't open with Fsociety, where I'm wrong?
so I have try to open directly from the directory and it give me this error:

```bash

python3 '/root/XSStrike/xsstrike.py' 

	XSStrike v3.1.1

Traceback (most recent call last):
  File "/root/XSStrike/xsstrike.py", line 32, in <module>
    from modes.crawl import crawl
  File "/root/XSStrike/modes/crawl.py", line 7, in <module>
    from core.filterChecker import filterChecker
  File "/root/XSStrike/core/filterChecker.py", line 1, in <module>
    from core.checker import checker
  File "/root/XSStrike/core/checker.py", line 2, in <module>
    from fuzzywuzzy import fuzz
ModuleNotFoundError: No module named 'fuzzywuzzy'

```
but I have that module...

**Comment by CRO-THEHACKER** [comment]
Try CHMOD ing it?

**Comment by b4s5** [comment]
yes don't work... if I try to launch directly in the XSSer directory it tell me the same error, if I try to launch with fsociety it gives me the first one that don't found the file or the directory

**Comment by Manisso** [comment]
https://github.com/s0md3v/XSStrike 
And Thnx For reporting the probem i will patch it soon

**Comment by Manisso** [comment]
@CRO-THEHACKER  https://github.com/Manisso/fsociety/invitations Go Go Go And Add me on facebook or Insta

**Comment by CRO-THEHACKER** [comment]
> ModuleNotFoundError: No module named 'fuzzywuzzy'

run:

> sudo pip install fuzzywuzzy
