### ISSUE TITLE
There are Missing parentheses!  

### ISSUE THREAD

**Issue by saurabh000345** [Manisso/fsociety#69]
https://github.com/Manisso/fsociety/blob/5a4388171a7149687bc902075f11ad3e573b0889/fsociety.py#L1138

**Comment by CRO-THEHACKER** [comment]
Thanks, I'll fix it.

**Comment by CRO-THEHACKER** [comment]
All fixed!

**Comment by saurabh000345** [comment]
> All fixed!

Bro, there are literally many missing parantheses, I updated your repository, and here's another issue:
https://github.com/Manisso/fsociety/blob/e67677fa851b7efaada8c240a223f72322761e12/fsociety.py#L1154

I dont know how many other areas have a similar issue. Did you have this for Python2 initially??

**Comment by CRO-THEHACKER** [comment]
I was thinking that we update the code for running it in python3 but, at the moment Python 2 is (/should) be the code exec to run Python (sudo python2 fsociety.py)

**Comment by saurabh000345** [comment]
> I was thinking that we update the code for running it in python3 but, at the moment Python 2 is (/should) be the code exec to run Python (sudo python2 fsociety.py)

Yeah I get that... although I am not the one who is executing the fsociety.py file, I'll make the required change in the install scripts to run the file properly though. All the best upgrading the code... I guess it will be tedious though.

**Comment by CRO-THEHACKER** [comment]
Yeah, updateing over 1000 lines of code for 1 version of code is hard but, can be done. I'll talk to some people in the fsociety team about updateing it. For now, I'm going to close the issue.
