### ISSUE TITLE
Dockerize this toolkit

### ISSUE THREAD

**Issue by jdrago999** [Manisso/fsociety#7]
First of all, this is awesome, and thank you for putting all this together.

There are a number of functions which require special libraries or other tools to be installed before they are available for use. I personally don't like running those tools on my main OS, and prefer running them in containers when possible.

I'd like to break this task into a few phases:

1. List all the tools that must be installed.
2. Decide which tools can run inside containers vs those which cannot run inside containers.
3. Of the tools which can run inside containers, decide which ones should run inside containers.
4. Prioritize the list of tools to be containerized, based on complexity vs value.
5. Start containerizing.

**Comment by thehappydinoa** [comment]
I will work on this

**Comment by thehappydinoa** [comment]
Ok @jdrago999 I added a [Dockerfile](https://github.com/Manisso/fsociety/commit/7116ef32961341529d0e3d6d94b5d81897711daf), let me know if it works for you

**Comment by jdrago999** [comment]
Hey @thehappydinoa I was thinking about it a different way. Usually a container is used for a single tool -- so instead of running `pip install beautifulsoup4 && pip install requests` in the host OS just so we can install `https://github.com/AeonDave/doork` it would be better to make sure that `doork` itself has a properly maintained `Dockerfile` and a working `fsociety/doork` Docker image on https://hub.docker.com/

Also, what happens if `doork` changes and now it requires a different version of `requests` or `beautifulsoup` or there are some other libraries required (eg: `libcrypto++-dev` or `libxml2-dev`) and simply running `pip install beautifulsoup4 && pip install requests` no longer works?

By pushing the responsibility of dependency management upstream into Docker containers, we gain the ability to have more reliable tools and reduce overall effort to make things work.

If the maintainers of the various upstream tools (like `doork`) want to participate in this effort, that would be great.

**Comment by thehappydinoa** [comment]
Hey @jdrago999 I honestly don't know enough about docker, would you be able to make a PR that does this?

**Comment by jdrago999** [comment]
> Hey @jdrago999 I honestly don't know enough about docker, would you be able to make a PR that does this?

Yes I would be happy to push this forward, working with other projects' maintainers as necessary.

**Comment by thehappydinoa** [comment]
@jdrago999 thank you

**Comment by mostafahussein** [comment]
@jdrago999 I might be able to help on this , But could you explain what are you planning to do ? Are we talking about a separate image for each tool and this case we will have a tool per container ?

**Comment by Isanderthul** [comment]
fyi trying out the docker commands I get the following error
[error.txt](https://github.com/Manisso/fsociety/files/1602361/error.txt)

**Comment by jdrago999** [comment]
@mostafahussein:
> Are we talking about a separate image for each tool and this case we will have a tool per container?

Yes precisely. And yes I realize that could be a lot of work, but I hope that having each of these tools running within an environment well-suited to them will alleviate the kinds of problems we run into when one tool has requirements that don't play well with another tool's requirements.

**Comment by Isanderthul** [comment]
I think that will be a maintenance nightmare, putting all the tools in one docker container makes more sense to me, then I can simply mount my ssh keys as an external volume, and any data partitions I want and then run the docker image and attach to it.

**Comment by thehappydinoa** [comment]
Hi all thank you so much for all the ideas, I am honestly not the best with docker so if you guys could make PRs as things go on that would be great.

**Comment by thehappydinoa** [comment]
@Isanderthul I am unable to view that file, could you create a new issue?

**Comment by Isanderthul** [comment]
new issue made https://github.com/Manisso/fsociety/issues/12

**Comment by alexcreek** [comment]
here you go https://github.com/Manisso/fsociety/pull/13
