### ISSUE TITLE
How would one uninstall this?

### ISSUE THREAD

**Issue by nerd7473** [Manisso/fsociety#70]
## Checkboxes

- [ ] Updated fsociety
- [ ] Issue does not already exist
- [ ] fsociety issue, not a tool issue

## Expected Result

```bash

```

## Actual Result

```bash

```

**Comment by CRO-THEHACKER** [comment]
Well. If your on Linux use: sudo rm -rf fsociety

**Comment by CRO-THEHACKER** [comment]
I can make up a uninstall if there is not already one.
