### ISSUE TITLE
Syntax Error!!

### ISSUE THREAD

**Issue by 2EASY4HACK** [Manisso/fsociety#71]
Welcome to Termux!

Wiki:            https://wiki.termux.com
Community forum: https://termux.com/community
IRC channel:     #termux on freenode
Gitter chat:     https://gitter.im/termux/termux
Mailing list:    termux+subscribe@groups.io

Search packages:   pkg search <query>
Install a package: pkg install <package>
Upgrade packages:  pkg upgrade
Learn more:        pkg help
✓ uname@localhost ~ $ fsociety
  File "/data/data/com.termux/files/usr/usr/share/doc/fsociety/fsociety.py", line 1154
    print "+----------------------------------------+"
                                                     ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("+----------------------------------------+")?

Here Syntax Error

    def main():
        sites = open(sitesfile).readlines()
        plugins = open(filepath).readlines()
        for site in sites:
            site = site.rstrip()
        for plugin in plugins:
            plugin = plugin.rstrip()
            scan(site, plugin)
            if resp not in Notfound:
                print "+----------------------------------------+"
                print "| current site:" + site
                print "| Found Plugin: " + plugin
                print "| Result:", resp

**Comment by CRO-THEHACKER** [comment]
This is a python error. PLEASE USE PYTHON 2 NOT 3!
