### ISSUE TITLE
Python3 Not Compatible

### ISSUE THREAD

**Issue by Tikam02** [Manisso/fsociety#74]
```
~/.fsociety$ python fsociety.py
  File "fsociety.py", line 1155
    print "| current site:" + site
                          ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("| current site:" + site)?
tikam@Hal:~/.fsociety$ 
```

It's written in python2, Convert it into python3

**Comment by CRO-THEHACKER** [comment]
Yes yes, I know.. I am still working on it.. It takes a long time to make everything to python3... For now - just run it in py2. Ok? Thanks!

**Comment by Tikam02** [comment]
@CRO-THEHACKER I want to contribute to it, by converting it into Python3 and adding more tools and modules for bug bounty hunting. Actually i Need a Tool like ALL FOR ONE - ONE FOR ALL.

**Comment by CRO-THEHACKER** [comment]
Yes yes, that would be great! But, you'll need yo get some rep here or talk to Manisso because, I can't give you anything.. You can talk to me on discord or Instagram if you would like too.

**Comment by Manisso** [comment]
https://github.com/Manisso/fsociety/tree/python3 :100:  To contribute contact - FB/DZMANISSO
