### ISSUE TITLE
Uninstall.sh

### ISSUE THREAD

**Issue by LieutenantVenom** [Manisso/fsociety#75]
Hey. Can you Please Make An **Uninstall Script for Fsociety?** There is an Install.sh in the Folder which installs it on the system and we can simply type "fsociety" in the terminal to Run it.. But if I want to Uninstall it, Using rm-rf Dost Work.. it Just deletes the folder. If i want it back and i try to install it, it Doesnt. So Please Create a Uninstall.sh which works like 'it wasnt there before' and also removes the fsociety command from the Terminal

**Comment by CRO-THEHACKER** [comment]
Yes - I can work on that with python3 - fsociety3..

**Comment by LieutenantVenom** [comment]
@CRO-THEHACKER Still Waiting For The Uninstall.sh . Is There Any Another Way to Remove installed Fsociety Rather than Wiping out Whole System and Start from 0?

**Comment by CRO-THEHACKER** [comment]
I'm sorry.. I've been at school doing test... Hard to code when you don't have an PC lol.. I'll get it done by this weekend..

**Comment by steve84835** [comment]
What is problem came again nd again by installing any type of package from my phone

**Comment by steve84835** [comment]
Please let me know that problem solution

**Comment by BlackZhadow** [comment]
hi this will work   
chmod a+rwx Desktop/fsociety

**Comment by BlackZhadow** [comment]
it wiil remove the lock and then u can delete it 
fsociety

**Comment by CRO-THEHACKER** [comment]
> it wiil remove the lock and then u can delete it 
> fsociety

To uninstall just do this:

First go to your fsociety dir so you can delete
```
chmod +x uninstall.sh && ./uninstall.sh
```
