### ISSUE TITLE
Smtp.py

### ISSUE THREAD

**Issue by Musicpac** [Manisso/fsociety#76]
## Expected Result
smtp service open up

## Actual Result
  File "smtp.py", line 3
   !DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http:// www.w3.org/TR/html4/strict.dtd"
    ^
SyntaxError: invalid syntax
Completed, click return to go back

**Comment by CRO-THEHACKER** [comment]
Under what menu?

**Comment by CRO-THEHACKER** [comment]
I don't see anything wrong. Could you please tell me what OS your using?

**Comment by CRO-THEHACKER** [comment]
If anyone needs this fixed then open this back up.. I'm open to fixing - but untill its an prob ill just keep it closed. Thanks!

**Comment by CRO-THEHACKER** [comment]
If anyone needs this fixed then open this back up.. I'm open to fixing - but untill its an prob ill just keep it closed. Thanks!
