### ISSUE TITLE
Adding CHMOD to install.sh

### ISSUE THREAD

**Issue by CRO-THEHACKER** [Manisso/fsociety#77]
Imma see if this works if I open this...

**Comment by B-BEN** [comment]
I cant install it on os x
after write ./install.sh
its going to install
then after enter my password to installing, install will be failed
what should I do?

**Comment by CRO-THEHACKER** [comment]
run "chmod +x {filename}"

**Comment by B-BEN** [comment]
I enter that
: 1. cd fsociety
2. chmod +x install.sh
3. ./install.sh
4. Enter Password

installation failed

**Comment by steve84835** [comment]
In which we installed??

**Comment by CRO-THEHACKER** [comment]
What do you mean? @steve84835

**Comment by CRO-THEHACKER** [comment]
OK! :+1: I fixed it now! All you need to is git the new version of fsociety to have the bug fixed! :1st_place_medal:
