### ISSUE TITLE
Cupp doesn´t work!

### ISSUE THREAD

**Issue by alberto64674yt** [Manisso/fsociety#78]
when y open cupp in password attacks y get that:

Traceback (most recent call last):
  File "/root/.fsociety/tools/cupp/cupp.py", line 40, in <module>
    import urllib.error
ImportError: No module named error
Completed, click return to go back^C Finishing up...

how to get to work plz?

**Comment by CRO-THEHACKER** [comment]
Try doing: 
`sudo -H pip install -y error`
Hope that fixes it!
