### ISSUE TITLE
__main__ 

### ISSUE THREAD

**Issue by kingmoe001** [Manisso/fsociety#82]
I execute the following:
root@domestic-intelligence-services:~# python2 fsociety
    Result:  /usr/bin/python2: can't find '__main__' module in 'fsociety'
How do I fix this?

**Comment by jiajia1714** [comment]
in put "pip install main"------------------ 原始邮件 ------------------
发件人: "kingmoe001"<notifications@github.com>
发送时间: 2019年6月28日(星期五) 中午1:14
收件人: "Manisso/fsociety"<fsociety@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: [Manisso/fsociety] __main__  (#82)



I execute the following:
 root@domestic-intelligence-services:~# python2 fsociety
 Result:  /usr/bin/python2: can't find 'main' module in 'fsociety'
 How do I fix this?
 
&mdash;

**Comment by kingmoe001** [comment]
![Screenshot from 2019-06-28 02-00-19](https://user-images.githubusercontent.com/48866202/60320628-512b5480-9948-11e9-9a53-283f138129ae.png)

**Comment by kingmoe001** [comment]
This is what was returned, any solutions to resolving this?

**Comment by jiajia1714** [comment]
Wait, let me think about it------------------ 原始邮件 ------------------
发件人: "kingmoe001"<notifications@github.com>
发送时间: 2019年6月28日(星期五) 下午2:00
收件人: "Manisso/fsociety"<fsociety@noreply.github.com>;
抄送: "jiajia1714"<360859939@qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [Manisso/fsociety] __main__  (#82)



This is what was returned, any solutions to resolving this?
 
&mdash;

**Comment by jiajia1714** [comment]
You open the tool folder
"ls"
Then send me the screenshot
---原始邮件---
发件人:"kingmoe001"<notifications@github.com>;
发送时间:2019年6月28日(星期五) 中午1:59
收件人:"Manisso/fsociety"<fsociety@noreply.github.com>;
抄送人:"jiajia1714"<360859939@qq.com>;"Comment"<comment@noreply.github.com>;
主题:Re: [Manisso/fsociety] __main__  (#82)



 
&mdash;

**Comment by jiajia1714** [comment]
updata pip
 install main
---原始邮件---
发件人:"kingmoe001"<notifications@github.com>;
发送时间:2019年6月28日(星期五) 中午1:59
收件人:"Manisso/fsociety"<fsociety@noreply.github.com>;
抄送人:"jiajia1714"<360859939@qq.com>;"Comment"<comment@noreply.github.com>;
主题:Re: [Manisso/fsociety] __main__  (#82)



 
&mdash;

**Comment by kingmoe001** [comment]
![Screenshot from 2019-06-28 02-55-07](https://user-images.githubusercontent.com/48866202/60323389-f4cc3300-994f-11e9-9b8d-e4d9a59e2cd8.png)

**Comment by jiajia1714** [comment]
Did your problem has been solved ?------------------ 原始邮件 ------------------
发件人: "kingmoe001"<notifications@github.com>
发送时间: 2019年6月28日(星期五) 下午2:54
收件人: "Manisso/fsociety"<fsociety@noreply.github.com>;
抄送: "jiajia1714"<360859939@qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [Manisso/fsociety] __main__  (#82)




 
&mdash;

**Comment by CRO-THEHACKER** [comment]
Just update pip and download the new git repo
