### ISSUE TITLE
setoolit 

### ISSUE THREAD

**Issue by pallxz** [Manisso/fsociety#84]
## Checkboxes

- [ ] Updated fsociety
- [ ] Issue does not already exist
- [ ] fsociety issue, not a tool issue

## Expected Result

```bash

```

## Actual Result

```bash

```

**Comment by pallxz** [comment]
it works but i need to know the adress to attack someone with another lan network ??

**Comment by CRO-THEHACKER** [comment]
It is impossible to connect to a different LAN network unless there's a port forward from the router or a VPN port forward. 

Example:

192.168.1.10 (this is you) 
To 10.0.0.4 (victim) 
DNS ERROR:
10.0.0.4 not found.
