### ISSUE TITLE
CUPP does't work -- How to do it work

### ISSUE THREAD

**Issue by Lars132** [Manisso/fsociety#86]
Just change the command from: 

os.system ("python% s / cupp.py -i"% self.installDir)

To:

os.system ("python3% s / cupp.py -i"% self.installDir) 

at line 809

**Comment by CRO-THEHACKER** [comment]
Hello, 

we do NOT use py3 yet.. 

[Issue marked as closed]

**Comment by Lars132** [comment]
Yes, but CUPP needs to use python3 until I know...

**Comment by CRO-THEHACKER** [comment]
Running it I'm terminal is possible
