### ISSUE TITLE
Fsociety Hack Tool Permission/Directory Problem

### ISSUE THREAD

**Issue by JxckoSmxcko** [Manisso/fsociety#87]
ok so I've been trying to download the fsociety hack tool for about 2-3 hours now, (im a huge fan of the show) and every single time ive gone to install the tool, these lines of code show up. Ive tried to change directory permissions by using the `chown JxckoSmxcko:staff ¿` command ("¿" is what my custom directory is called) but the same strings of code would show up underneath the cool FSOCIETY INSTALLER title every. single. time. I'm going crazy, please help me. (apologise in case it is an easy fix, im very tired)

`fatal: could not create work tree dir '/usr/local/fsociety': Permission denied
./install.sh: line 73: /usr/local/fsociety/fsociety: No such file or directory
chmod: /usr/local/fsociety/fsociety: No such file or directory
cp: /usr/local/fsociety/fsociety: No such file or directory
cp: /usr/local/fsociety/fsociety.cfg: No such file or directory
rm: /usr/local/fsociety/fsociety: No such file or directory
[✘] Installation failed! [✘] `

**Comment by kdaoudieh** [comment]
did you try to use `Sudo` maybe or chek the files permission or maybe if the file doesn't exist try to create it manually?

**Comment by CRO-THEHACKER** [comment]
What os?

**Comment by JxckoSmxcko** [comment]
I'm using macOS and i have already checked the file permissions. Ive made it so that the install.py can read, write and execute but it still doesn't work. However, i have been spending the last couple of days figuring out how to instal VirtualBox with a Kali Linux virtual machine and it works, majority of the hack tools that is.

**Comment by CRO-THEHACKER** [comment]
Hm.. Well there's isn't anything going wrong with my stuff so, it would have to be your MacBook.. macOS 10.14 Mojave is working..

**Comment by 0x00nyx** [comment]
I also see that there is a lot of errors with the current tool installers. Almost none of the applications or scripts work for me. Going to do some peeking into the source code over the next bit to pinpoint what I can then update later here.

**Comment by CRO-THEHACKER** [comment]
make sure you use `sudo`!

**Comment by 0x00nyx** [comment]
I have used `sudo` when using the command (ex `sudo fsociety`) but I get multiple errors. Mostly that the tools are missing (ex after installing fsociety tools I try to use `nmap` but `nmap` is missing). I still can't seem to get the tools to work at all.

Note: I'm using TailsOS instead of Kali Linux

**Comment by CRO-THEHACKER** [comment]
Can you please send the errors.

**Comment by 0x00nyx** [comment]
Here is `nmap`. It has the screen just before it saying that it's cloning into the directory, then this appears:

```
sh: 1: nmap: not found

Click [Return] to continue
```

Here is `cupp`:

```
'/home/amnesia/.fsociety/tools/cupp'...
     dP""b8 88   88 88""Yb 88""Yb
    dP   `" 88   88 88__dP 88__dP
    Yb      Y8   8P 88"""  88"""
     YboodP `YbodP' 88     88
     
python: can't open file '/home/amnesia/.fsociety/tools/cupp/cupp.py': [Errno 2] No such file or directory
Completed, click return to go back
```

**Comment by CRO-THEHACKER** [comment]
See if you can find the real `.fsociety` dir

**Comment by CRO-THEHACKER** [comment]
Closed
