### ISSUE TITLE
Missing parentheses

### ISSUE THREAD

**Issue by ShodiyorK** [Manisso/fsociety#88]
File "/data/data/com.termux/files/usr/usr/share/doc/fsociety/fsociety.py", line 1174
    print "+----------------------------------------+"
                                                     ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("+----------------------------------------+")?

OS: Android

**Comment by CRO-THEHACKER** [comment]
making push to git

**Comment by CRO-THEHACKER** [comment]
added and pushed.
