### ISSUE TITLE
termux error line 2: python: command not found

### ISSUE THREAD

**Issue by lybchikfreed** [Manisso/fsociety#89]
## Checkboxes

- [ ] Updated fsociety
- [ ] Issue does not already exist
- [x ] fsociety issue, not a tool issue

## Expected Result

```bash
fsociety launch
```

## Actual Result

```bash
$ fsociety
/data/data/com.termux/files/usr/bin/fsociety: line 2: python: command not found
```

**Comment by CRO-THEHACKER** [comment]
Sounds good. I'll take a look in a bit.

**Comment by CRO-THEHACKER** [comment]
This seems to be on your device... Are you sure python is installed?

**Comment by CRO-THEHACKER** [comment]
please open if it is.
