### ISSUE TITLE
Program is not working

### ISSUE THREAD

**Issue by diamond95** [Manisso/fsociety#90]
## Checkboxes

- [ x] Updated fsociety
- [x ] Issue does not already exist
- [ ] fsociety issue, not a tool issue

## Expected Result

```bash
Traceback (most recent call last):
  File "/root/.fsociety/tools/cupp/cupp.py", line 40, in <module>
    import urllib.error
ImportError: No module named error


python: can't open file '/root/.fsociety/tools/XSStrike/xsstrike': [Errno 2] No such file or directory
etc...

```

## What I did

```bash
chmod +x install.sh 
fsociety 
entering any number for starting tool. 
```

##OS
Kali linux

**Comment by CRO-THEHACKER** [comment]
All you need to do is

pip install urllib

**Comment by diamond95** [comment]
root@mrrobot:~/Desktop/fsociety# pip install urllib
Collecting urllib
Could not install packages due to an EnvironmentError: 404 Client Error: Not Found for url: https://pypi.org/simple/urllib/

**Comment by CRO-THEHACKER** [comment]
Hm.. This is an issue with you.. Please feel free to join the discord and we can see about trying to fix your problem.

**Comment by ashXbd** [comment]
please solve this issue.
File "/home/ravan666/opt/fsociety/fsociety.py", line 1194
    print "-------------------------"
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(...)?

**Comment by Piston0101** [comment]
> 

Same Problem

**Comment by Vstar0116** [comment]
> please solve this issue. File "/home/ravan666/opt/fsociety/fsociety.py", line 1194 print "-------------------------" ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ SyntaxError: Missing parentheses in call to 'print'. Did you mean print(...)?

same problem

**Comment by ghostcodelogik13** [comment]
I tried working on it as well but just decided to use the python 3 version which works easier

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
