### ISSUE TITLE
Anyway to get this to run om mac?

### ISSUE THREAD

**Issue by eren123danyel** [Manisso/fsociety#91]
## Checkboxes

- [ X] Updated fsociety
- [ ] Issue does not already exist
- [ ] fsociety issue, not a tool issue

Does anyone know a way to get this working on mac? Fsociety installs succesfully but all tools will throw a "command: "TOOLNAME" not found"

**Comment by CRO-THEHACKER** [comment]
Try and reinstall and check path.. Fix path, this is can be set.
