### ISSUE TITLE
Missing parentheses on Termux

### ISSUE THREAD

**Issue by Azazel771** [Manisso/fsociety#92]
File "/data/data/com.termux/files/usr/usr/share/doc/fsociety/fsociety.py", line 1194
    print "-------------------------"
          ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("-------------------------")?

**Comment by up2smoke** [comment]
Same !
I looked into the script.. on every print commant are the ( ) missing. 
YouTube only Show that the Script Work. But Not how to Install. 
Be carefull !!! 
Maybe its only a scammer !!!!

**Comment by Azazel771** [comment]
> Be carefull !!!
> Maybe its only a scammer !!!!

I don't think so, if you look at the readme, you'll see that it was made for python 2.x which had different Syntax then the new Python 3.8. it's not a scam merely outdated, also it ports the functions used so it technically can't even be a scam. Sad that the parantheses are missing tho

**Comment by up2smoke** [comment]
$ python2 fsociety
python2: can't open file 'fsociety': [Errno 2] No such file or directory
$ fsociety                                        /data/data/com.termux/files/usr/bin/fsociety: line 2: python: command not found
$ python
The program python is not installed. Install it by executing:
 pkg install python
$ |

**Comment by up2smoke** [comment]
$ python2 /data/data/com.termux/files/usr/bin/fsociety
  File "/data/data/com.termux/files/usr/bin/fsociety", line 2
    python /data/data/com.termux/files/usr/usr/share/doc/fsociety/fsociety.py ${1+"$@"}
                                                                              ^
SyntaxError: invalid syntax
$

**Comment by Azazel771** [comment]
I meant the python version 2 and not python2

**Comment by up2smoke** [comment]
YT Video from the readme says type "python2" ..

**Comment by Azazel771** [comment]
Yes nevermind I was confused for a second, it still only errors on those parantheses so I think it's real but it's outdated

**Comment by up2smoke** [comment]
U read the readme?
Readme says python 2.7 & python 3.
Both are installed and nothing work

**Comment by up2smoke** [comment]
I will try it on my Raspberry Zero W with KaliLinux

**Comment by Azazel771** [comment]
I don't think that'll work because the parantheses are still missing, well I guess they just forgot the parantheses

**Comment by up2smoke** [comment]
so enter " cp /data/data/com.termux/files/usr/usr/share/doc/fsociety/fsociety.py /sdcard "and edit by ur owm. U will See, when u fix it ,the Script will give n next Error in a diffrent Line. Fix it again and again an next Line. Again and again. 
What a rubbish of code

**Comment by up2smoke** [comment]
or enter "apt install nano" and than "nano /data/data/com.termux/files/usr/usr/share/doc/fsociety/fsociety.py"

**Comment by Azazel771** [comment]
They literally just forgot the parantheses, shouldn't call that rubbish, after all, using others scripts is optional and should not be seen as self-evident, so please give credit where credit is due. If you don't want to use it then don't everyone get's things wrong sometimes after all

**Comment by up2smoke** [comment]
I replace everythink and try to Run again

re/doc/fsociety/fsociety.py
$ fsociety
  File "/data/data/com.termux/files/usr/usr/share/doc/fsociety/fsociety.py", line 1930
    except urllib2.HTTPError, e:
                            ^
SyntaxError: invalid syntax
$

How i can give a credit, If this is not good writing. 
Readme says tested on..... Whats tested?  Nothing work, so what?

**Comment by up2smoke** [comment]
Oke, i can confirm, its Work on the raspberry Pi, without any problems, after Installation. 
So maybe its termux the culprit.

I'm realy sorry for my bad language

**Comment by Azazel771** [comment]
Huh that's weird, well it could be I don't really know

**Comment by kismatboy** [comment]
> Same !
> I looked into the script.. on every print commant are the ( ) missing.
> YouTube only Show that the Script Work. But Not how to Install.
> Be carefull !!!
> Maybe its only a scammer !!!!

if you want to run fsociety in termux:
1.  update termux latest version
 2.  'pkg install python2'
3. 'pkg install git'
4.  'git clone https://github.com/Manisso/fsociety.git'
5. 'cd fsociety'
6. './install.sh'
7. 'python2 fsociety.py'

i had same issue but
now i just installed and run just now

**Comment by Azazel771** [comment]
Ohh thanks it works now

**Comment by Paulanthonyrocks** [comment]
Not sure if it's working

**Comment by CRO-THEHACKER** [comment]
> Not sure if it's working

Run as python2 not 3. Python3 is at https://github.com/CRO-THEHACKER/fsociety3

**Comment by caerere** [comment]
> 

Life saver man
