### ISSUE TITLE
Uninstall removes the majority of Parrot OS

### ISSUE THREAD

**Issue by skluthe** [Manisso/fsociety#99]
## Checkboxes

- [x ] Updated fsociety
- [x ] Issue does not already exist
- [x ] fsociety issue, not a tool issue

## Expected Result
Only removes the tools installed by this tool

## Actual Result
Removes all kinds of fun things like MATE, Metasploit, parrot-interface, etc. Would have rebooted into a non-working system if I wasn't paying attention.

**Comment by CRO-THEHACKER** [comment]
could you please give more detail?

**Comment by skluthe** [comment]
Ran the uninstall script on the latest Parrot OS version and it uninstalled
the desktop environment. Didn't have a chance to grab everything it was
removing unfortunately.

If you spin up a ParrotOS VM, install fsociety, then uninstall it after you
install a few tools it'll remove MATE as well as some parrot specific
packages. Think it removes something that's a dependency for these
packages.

**Comment by CRO-THEHACKER** [comment]
Okay, let me take a look. It'll be in the new version of fs3. So- wait the for update is all I can say for a few days.

**Comment by yahu1031** [comment]
I guess better modify the code not to remove python2.* and python3.* packages from the system. because this is causing a huge damage to the parrot os.

**Comment by CRO-THEHACKER** [comment]
OK, update almost done

**Comment by CRO-THEHACKER** [comment]
Okay, try updating now; pushing new updates.
